
MACHINES = {
    :vm1 => {
          :box_name => "bento/ubuntu-20.04",
          :cpus => 2,
          :memory => 1024,
          :net => [
                     {ip: '10.10.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "lab-net"},
                  ]
    },
    :vm2 => {
          :box_name => "bento/ubuntu-20.04",
          :cpus => 2,
          :memory => 1256,
          :net => [
                     {ip: '10.10.1.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "lab-net"},
                  ]
    },
}
  
  Vagrant.configure("2") do |config|
  
    MACHINES.each do |boxname, boxconfig|
      
      config.vm.define boxname do |box|

#          box.vm.synced_folder '.', '/vagrant', disabled: true
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
          end
          
          if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
          end
          
          box.vm.provider "virtualbox" do |v|
            # Set VM RAM size and CPU count
            v.memory = boxconfig[:memory]
            v.cpus = boxconfig[:cpus]
#            v.default_nic_type = "virtio"
            v.name = boxname.to_s
          end
      end                    
    end

end
