version: '3.1'

services:

  db:
    image: postgres:13
    restart: always    
    environment:
      POSTGRES_PASSWORD: 123456xx
      PGDATA: /srv/db
    volumes:
      - pg_db:/srv/db
      - ./test_dump.sql:/root/test_dump.sqlp

volumes:
  pg_db:
