version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456xx
      PGDATA: /srv/db      
    volumes:
      - db:/srv/db
      - bckp:/srv/backup

  db2:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456xx
      PGDATA: /srv/db      
    volumes:
      - db2:/srv/db
      - bckp:/srv/backup

volumes:
  db:
  db2:
  bckp:
